apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: dettinjo/auth_service:v2
        ports:
        - containerPort: 8001
        env:
        - name: AUTH_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_PORT
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET_KEY
        - name: DB_MOUNT_POINT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_MOUNT_POINT
        - name: DB_NAME_AUTH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME_AUTH
        volumeMounts:
        - name: db-storage
          mountPath: /var/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-auth-pvc