apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-auth-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: db-auth-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-shortener-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: db-shortener-pv